### PR TITLE
PR Elasticsearch 2.3.x

### PR DESCRIPTION
**Pull request by bloublou2014**
With elasticsearch 2.3.2 a couple of updates have to be done :

add plugin-descriptor.properties file
add compiled kibana on _site directory
add install instruction on readme.md

### CODE REVIEW

**Comment by lee-elenbaas** [comment]
I do not understand the move from dist to _site - it makes looking at the actual changes very hard
also this PR has conflicts that needs to be resolved

**Comment by bloublou2014** [comment]
- dist ==> _site : when installing from elasticsearch 'plugin install repo/kibana'  website should be available on _site directory. Since kibana 3 has no server and default config.js point to "http://" + window.location.hostname + ":9200", installation upon elasticsearch as a plugin is a solution. 
- conflicts : how can i help , there is not soo much files and most of the time it's space diff ?

**Comment by lee-elenbaas** [comment]
regarding the conflict - pull latest version from this repo - solve all that needs to be solved on your computer, then commit into your branch

**Comment by bloublou2014** [comment]
Close pull request to edit conflicts locally

**Pull request closed without merging**
